service:
  name: ${self:provider.appName}-address-book

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  stage: ${opt:stage}
  appName: space
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - Fn::ImportValue: 'AppDynamoDbTableArn-${self:provider.stage}'
        - Fn::Join:
          - ""
          - - Fn::ImportValue: 'AppDynamoDbTableArn-${self:provider.stage}'
            - "/*"

plugins:
  - serverless-jetpack

custom:
  jetpack:
    base: "../../"

functions:
  createIdentity:
    handler: dist/index.createIdentity
    environment:
      ENV: ${self:provider.stage}
    events:
      - http:
          method: post
          path: /identities
          cors: true
          request:
            schema:
              application/json: ${file(schemas/create-identity.json)}
  getIdentityByUsername:
    handler: dist/index.getIdentityByUsername
    environment:
      ENV: ${self:provider.stage}
    events:
      - http:
          method: get
          path: /identities/username/{username}
          cors: true
          request:
            parameters:
              paths:
                username: true
  getIdentityByAddress:
    handler: dist/index.getIdentityByAddress
    environment:
      ENV: ${self:provider.stage}
    events:
      - http:
          method: get
          path: /identities/address/{address}
          cors: true
          request:
            parameters:
              paths:
                address: true
