service:
  name: ${self:provider.appName}-billing

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  stage: ${opt:stage}
  appName: space
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource:
        - Fn::ImportValue: 'AppDynamoDbTableArn-${self:provider.stage}'
        - Fn::Join:
          - ""
          - - Fn::ImportValue: 'AppDynamoDbTableArn-${self:provider.stage}'
            - "/*"
    - Effect: Allow
      Action:
        - execute-api:ManageConnections
      Resource:
        - "arn:aws:execute-api:${self:provider.region}:${ssm:org-arn}:${self:provider.executeApi.${self:provider.stage}}/${opt:stage}/*"
  executeApi:
    dev: 413h5xnqp8

plugins:
  - serverless-jetpack

custom:
  jetpack:
    base: "../../"

package:
  exclude:
    - "**/node_modules/aws-sdk/**" # included on Lambda.

functions:
  createStripeSubscription:
    handler: dist/stripe/createSubscription.handler
    environment:
      ENV: ${self:provider.stage}
      STRIPE_SECRET: ${ssm:stripe-sk-${self:provider.stage}~true}
    events:
      - http:
          method: post
          path: /stripe/create-subscription
          cors: true

  stripeWebhook:
    handler: dist/stripe/webhook.handler
    environment:
      ENV: ${self:provider.stage}
      STRIPE_SECRET: ${ssm:stripe-sk-${self:provider.stage}~true}
      STRIPE_WEBHOOK_SECRET: ${ssm:stripe-wh-${self:provider.stage}~true}
      PRO_PLAN_ID: price_1HbnI7CEFZDhKYzKKfCbtHnX
      APIG_ENDPOINT: ${self:provider.executeApi.${self:provider.stage}}.execute-api.us-west-2.amazonaws.com/${opt:stage}
    events:
      - http:
          method: post
          path: /stripe/webhook
          cors: true

  cancelStripeSubscription:
    handler: dist/stripe/cancelSubscription.handler
    environment:
      ENV: ${self:provider.stage}
      STRIPE_SECRET: ${ssm:stripe-sk-${self:provider.stage}~true}
    events:
      - http:
          method: post
          path: /stripe/cancel-subscription
          cors: true
          authorizer: arn:aws:lambda:${self:provider.region}:${ssm:org-arn}:function:space-rest-${self:provider.stage}-authorizer

  getAccount:
    handler: dist/account.handler
    environment:
      ENV: ${self:provider.stage}
    events:
      - http:
          method: get
          path: /account
          cors: true
          authorizer: arn:aws:lambda:${self:provider.region}:${ssm:org-arn}:function:space-rest-${self:provider.stage}-authorizer

  getPaymentDetails:
    handler: dist/crypto/getPaymentDetails.handler
    environment:
      ENV: ${self:provider.stage}
    events:
      - http:
          method: get
          path: /crypto/get-payment-details
          cors: true
          authorizer: arn:aws:lambda:${self:provider.region}:${ssm:org-arn}:function:space-rest-${self:provider.stage}-authorizer