service:
  name: ${self:provider.appName}-billing

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  stage: ${opt:stage}
  appName: space
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource:
        - Fn::ImportValue: 'AppDynamoDbTableArn-${self:provider.stage}'
        - Fn::Join:
          - ""
          - - Fn::ImportValue: 'AppDynamoDbTableArn-${self:provider.stage}'
            - "/*"

plugins:
  - serverless-jetpack

custom:
  jetpack:
    base: "../../"

package:
  exclude:
    - "**/node_modules/aws-sdk/**" # included on Lambda.

functions:
  createWallet:
    handler: dist/index.createWallet
    environment:
      ENV: ${self:provider.stage}
    events:
      - http:
          method: post
          path: /wallet
          cors: true

  claimWallet:
    handler: dist/index.claimWallet
    environment:
      ENV: ${self:provider.stage}
    events:
      - http:
          method: post
          path: /wallet/{key}
          cors: true
          authorizer: arn:aws:lambda:${self:provider.region}:${ssm:org-arn}:function:space-rest-${self:provider.stage}-authorizer
          request:
            parameters:
              paths:
                key: true

  createStripeCustomer:
    handler: dist/create-stripe-customer.handler
    environment:
      ENV: ${self:provider.stage}
      STRIPE_WEBHOOK_SECRET: ${ssm:stripe-sk-${self:provider.stage}~true}
    events:
      - http:
          method: post
          authorizer: arn:aws:lambda:${self:provider.region}:${ssm:org-arn}:function:space-rest-${self:provider.stage}-authorizer
          path: /stripe-customer
          cors: true

  paymentStatusWebhook:
    handler: dist/index.paymentStatusWebhook
    environment:
      ENV: ${self:provider.stage}
    events:
      - http:
          method: post
          path: /payments
          cors: true

  stripeWebhook:
    handler: dist/webhooks/stripe.handler
    environment:
      ENV: ${self:provider.stage}
      STRIPE_WEBHOOK_SECRET: ${ssm:stripe-sk-${self:provider.stage}~true}
    events:
      - http:
          method: post
          path: /webhooks/stripe
          cors: true